//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidPay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class card
    {
        public int id { get; set; }
        public string card1 { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<int> user_id { get; set; }
    }
}
